defaults:
  - _self_ 
  - net: default 

seed: 42

net:
  depth: 3
  width: 64
  num_classes: 6

trainer:
  max_epochs: 100
  log_every_n_steps: 10

dataset:
  data_dir: "./data"
  batch_size: 32
  val_split: 0.2

wandb :
  project: "FDS_PROJECT"
  entity: "catairu-sapienza-universit-di-roma"
  name: "max_epochs{max_epochs}_bs{batch_size}_valsplit{val_split}_depth{depth}_width{width}_opt{optimizer._target_}_lr{optimizer.lr}_hsize{rnn_block.hidden_size}_nlayers{rnn_block.num_layers}"

