defaults:
  - _self_ 
  - net: default 

seed: 42

net:
  depth: 2
  width: 128
  num_classes: 6

trainer:
  max_epochs: 100
  log_every_n_steps: 10
  accelerator: "gpu"
  devices: [0]

k_folds: 5

dataset:
  data_dir: "./data"
  batch_size: 16
  val_split: 0.2

wandb :
  project: "FDS_PROJECT"
  entity: "catairu-sapienza-universit-di-roma"
  name: "maxepochs${trainer.max_epochs}_bs${dataset.batch_size}_valsplit${dataset.val_split}_depth${net.depth}_width${net.width}_opt${net.optimizer._target_}_lr${net.optimizer.lr}_hsize${net.rnn_block.hidden_size}_nlayers${net.rnn_block.num_layers}"